version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    entrypoint: ["sh", "/app/entrypoint.sh"]
    restart: always
